module changed on disk: /home/lemaigna/applis/blender-2.74-rc2-linux-glibc211-x86_64/2.74/scripts/addons/object_print3d_utils/__init__.py reloading...


================================

Pre-assessment for group L


================================

Global unit scale: 0.0010000000474974513
	 Fine, millimeters


--------------------------------



--------------------------------

Object <Doge>:
	Raw dimensions (mm): 64, 57, 73.96422576904297
	Volume: 274641mm3
[WW]	Object has no texture!
	3D toolbox analyse:
		Non Manifold Edge: 0
		Bad Contig. Edges: 0
		Intersect Face: 0
		Zero Faces: 0
		Zero Edges: 0
		Non-Flat Faces: 0
		Thin Faces: 0
		Sharp Edge: 0
[WW]		Overhang Face: 715
	Exporting to <Doge.stl>...
		Export ok


================================

SUMMARY

- 1 part(s) submitted
- 0 part(s) use a texture
[EE]	No texture!
- total volume: 274641
	 Ok, below limit
- 1 warnings
- 1 errors
found bundled python: /home/lemaigna/applis/blender-2.74-rc2-linux-glibc211-x86_64/2.74/python
read blend: /home/lemaigna/src/cs211-visual-computing/milestone 2/pre-assessment/../submissions/L//such_3d_wow.blend

Blender quit
