module changed on disk: /home/lemaigna/applis/blender-2.74-rc2-linux-glibc211-x86_64/2.74/scripts/addons/object_print3d_utils/__init__.py reloading...


================================

Pre-assessment for group S


================================

Global unit scale: 0.0010000000474974513
	 Fine, millimeters


--------------------------------



--------------------------------

Object <Lamp>:
[WW]	Not a mesh, ignoring
Object <Camera>:
[WW]	Not a mesh, ignoring
Object <Cube.001>:
	Raw dimensions (mm): 40, 36, 56.96278762817383
	Volume: 84143mm3
	Object use texture <Material Diffuse Color>
	Object use texture <trunk.jpg>
	Object use texture <foliage.jpg>
	Object use texture <Foilage Diffuse Color>
	3D toolbox analyse:
		Non Manifold Edge: 0
		Bad Contig. Edges: 0
[WW]		Intersect Face: 218
[WW]		Zero Faces: 14
		Zero Edges: 0
[WW]		Non-Flat Faces: 258
[WW]		Thin Faces: 8
		Sharp Edge: 0
[WW]		Overhang Face: 200
	Exporting to <Cube.001.stl>...
		Export ok


================================

SUMMARY

- 1 part(s) submitted
- 1 part(s) use a texture
- total volume: 84143
	 Ok, below limit
- 7 warnings
- 0 errors
found bundled python: /home/lemaigna/applis/blender-2.74-rc2-linux-glibc211-x86_64/2.74/python
read blend: /home/lemaigna/src/cs211-visual-computing/milestone 2/pre-assessment/../submissions/S//lastTree3.blend

Blender quit
